server:
  servlet:
    context-path: /yumyum
spring:
  datasource:
    #    AWS setting:
    #    driver-class-name: org.mariadb.jdbc.Driver
    #    url: jdbc:mariadb://ssafydb.cr7qoevh9p3x.ap-northeast-2.rds.amazonaws.com?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    #    username: root
    #    password: password
    #    local setting:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:8090/ssafydb?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: wnsgus123
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 256MB
      max-request-size: 256MB

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: update
  messages:
    basename: i18n/exception
    encoding: UTF-8

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE